// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phwyrjrdlpzirfiyjqep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBod3lyanJkbHB6aXJmaXlqcWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MTA1MzIsImV4cCI6MjA1NzM4NjUzMn0.UDmctXpGuEFndhNwQYN8d_l_nESJEs1Q5P04oVLensc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);